/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 现金资产表
 */
@ApiModel(description = "现金资产表")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-13T11:09:51.307434+08:00[Asia/Shanghai]")
public class BalanceOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private String total;

  public static final String SERIALIZED_NAME_ASSET_TOTAL = "assetTotal";
  @SerializedName(SERIALIZED_NAME_ASSET_TOTAL)
  private String assetTotal;

  public static final String SERIALIZED_NAME_AVAILABLE_ASSET_TOTAL = "availableAssetTotal";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_ASSET_TOTAL)
  private String availableAssetTotal;

  public static final String SERIALIZED_NAME_MARKET_PRICE = "marketPrice";
  @SerializedName(SERIALIZED_NAME_MARKET_PRICE)
  private String marketPrice;

  public static final String SERIALIZED_NAME_LOCKED = "locked";
  @SerializedName(SERIALIZED_NAME_LOCKED)
  private String locked;

  public static final String SERIALIZED_NAME_AVAILABLE = "available";
  @SerializedName(SERIALIZED_NAME_AVAILABLE)
  private String available;

  public static final String SERIALIZED_NAME_INDEBTED = "indebted";
  @SerializedName(SERIALIZED_NAME_INDEBTED)
  private String indebted;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPE = "accountType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE)
  private Integer accountType;


  public BalanceOpenApiVo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BalanceOpenApiVo accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * 交易账号
   * @return accountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "交易账号")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public BalanceOpenApiVo tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public BalanceOpenApiVo userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public BalanceOpenApiVo total(String total) {
    
    this.total = total;
    return this;
  }

   /**
   * 总资产
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "总资产")

  public String getTotal() {
    return total;
  }


  public void setTotal(String total) {
    this.total = total;
  }


  public BalanceOpenApiVo assetTotal(String assetTotal) {
    
    this.assetTotal = assetTotal;
    return this;
  }

   /**
   * 对应的usdt计价总资产
   * @return assetTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "对应的usdt计价总资产")

  public String getAssetTotal() {
    return assetTotal;
  }


  public void setAssetTotal(String assetTotal) {
    this.assetTotal = assetTotal;
  }


  public BalanceOpenApiVo availableAssetTotal(String availableAssetTotal) {
    
    this.availableAssetTotal = availableAssetTotal;
    return this;
  }

   /**
   * 对应的usdt计价可用总资产
   * @return availableAssetTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "对应的usdt计价可用总资产")

  public String getAvailableAssetTotal() {
    return availableAssetTotal;
  }


  public void setAvailableAssetTotal(String availableAssetTotal) {
    this.availableAssetTotal = availableAssetTotal;
  }


  public BalanceOpenApiVo marketPrice(String marketPrice) {
    
    this.marketPrice = marketPrice;
    return this;
  }

   /**
   * 实时价格
   * @return marketPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "实时价格")

  public String getMarketPrice() {
    return marketPrice;
  }


  public void setMarketPrice(String marketPrice) {
    this.marketPrice = marketPrice;
  }


  public BalanceOpenApiVo locked(String locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * 已冻结资产。
   * @return locked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "已冻结资产。")

  public String getLocked() {
    return locked;
  }


  public void setLocked(String locked) {
    this.locked = locked;
  }


  public BalanceOpenApiVo available(String available) {
    
    this.available = available;
    return this;
  }

   /**
   * 可用资产
   * @return available
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "可用资产")

  public String getAvailable() {
    return available;
  }


  public void setAvailable(String available) {
    this.available = available;
  }


  public BalanceOpenApiVo indebted(String indebted) {
    
    this.indebted = indebted;
    return this;
  }

   /**
   * 负债资产
   * @return indebted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "负债资产")

  public String getIndebted() {
    return indebted;
  }


  public void setIndebted(String indebted) {
    this.indebted = indebted;
  }


  public BalanceOpenApiVo createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 创建时间
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "创建时间")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public BalanceOpenApiVo updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 更新时间
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "更新时间")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public BalanceOpenApiVo accountType(Integer accountType) {
    
    this.accountType = accountType;
    return this;
  }

   /**
   * 1现货，2期权，3期货，4杠杆账户
   * @return accountType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1现货，2期权，3期货，4杠杆账户")

  public Integer getAccountType() {
    return accountType;
  }


  public void setAccountType(Integer accountType) {
    this.accountType = accountType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceOpenApiVo balanceOpenApiVo = (BalanceOpenApiVo) o;
    return Objects.equals(this.id, balanceOpenApiVo.id) &&
        Objects.equals(this.accountId, balanceOpenApiVo.accountId) &&
        Objects.equals(this.tokenId, balanceOpenApiVo.tokenId) &&
        Objects.equals(this.userId, balanceOpenApiVo.userId) &&
        Objects.equals(this.total, balanceOpenApiVo.total) &&
        Objects.equals(this.assetTotal, balanceOpenApiVo.assetTotal) &&
        Objects.equals(this.availableAssetTotal, balanceOpenApiVo.availableAssetTotal) &&
        Objects.equals(this.marketPrice, balanceOpenApiVo.marketPrice) &&
        Objects.equals(this.locked, balanceOpenApiVo.locked) &&
        Objects.equals(this.available, balanceOpenApiVo.available) &&
        Objects.equals(this.indebted, balanceOpenApiVo.indebted) &&
        Objects.equals(this.createdAt, balanceOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, balanceOpenApiVo.updatedAt) &&
        Objects.equals(this.accountType, balanceOpenApiVo.accountType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountId, tokenId, userId, total, assetTotal, availableAssetTotal, marketPrice, locked, available, indebted, createdAt, updatedAt, accountType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    assetTotal: ").append(toIndentedString(assetTotal)).append("\n");
    sb.append("    availableAssetTotal: ").append(toIndentedString(availableAssetTotal)).append("\n");
    sb.append("    marketPrice: ").append(toIndentedString(marketPrice)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    indebted: ").append(toIndentedString(indebted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

