/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 充值订单OpenAPI响应VO
 */
@ApiModel(description = "充值订单OpenAPI响应VO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T15:36:39.334120+08:00[Asia/Shanghai]")
public class DepositOrderOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_TOKEN_ID = "chainTokenId";
  @SerializedName(SERIALIZED_NAME_CHAIN_TOKEN_ID)
  private String chainTokenId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private String quantity;

  public static final String SERIALIZED_NAME_FROM_ADDRESS = "fromAddress";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS)
  private String fromAddress;

  public static final String SERIALIZED_NAME_WALLET_ADDRESS = "walletAddress";
  @SerializedName(SERIALIZED_NAME_WALLET_ADDRESS)
  private String walletAddress;

  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Integer status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  private String subUserId;


  public DepositOrderOpenApiVo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 充值订单ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "充值订单ID")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public DepositOrderOpenApiVo tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * 币种ID
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "币种ID")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public DepositOrderOpenApiVo chainTokenId(String chainTokenId) {
    
    this.chainTokenId = chainTokenId;
    return this;
  }

   /**
   * 链上币种ID
   * @return chainTokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "链上币种ID")

  public String getChainTokenId() {
    return chainTokenId;
  }


  public void setChainTokenId(String chainTokenId) {
    this.chainTokenId = chainTokenId;
  }


  public DepositOrderOpenApiVo quantity(String quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * 充值数量
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "充值数量")

  public String getQuantity() {
    return quantity;
  }


  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  public DepositOrderOpenApiVo fromAddress(String fromAddress) {
    
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * 来源地址
   * @return fromAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "来源地址")

  public String getFromAddress() {
    return fromAddress;
  }


  public void setFromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
  }


  public DepositOrderOpenApiVo walletAddress(String walletAddress) {
    
    this.walletAddress = walletAddress;
    return this;
  }

   /**
   * 钱包地址
   * @return walletAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "钱包地址")

  public String getWalletAddress() {
    return walletAddress;
  }


  public void setWalletAddress(String walletAddress) {
    this.walletAddress = walletAddress;
  }


  public DepositOrderOpenApiVo txId(String txId) {
    
    this.txId = txId;
    return this;
  }

   /**
   * 交易ID（区块链交易哈希）
   * @return txId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "交易ID（区块链交易哈希）")

  public String getTxId() {
    return txId;
  }


  public void setTxId(String txId) {
    this.txId = txId;
  }


  public DepositOrderOpenApiVo status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * 充值状态： 0: 初始化 INIT; 1: 完成 已到账; 2: 处理中 充值中; 3: 失败
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "充值状态： 0: 初始化 INIT; 1: 完成 已到账; 2: 处理中 充值中; 3: 失败")

  public Integer getStatus() {
    return status;
  }


  public void setStatus(Integer status) {
    this.status = status;
  }


  public DepositOrderOpenApiVo createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 创建时间（毫秒时间戳）
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "创建时间（毫秒时间戳）")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public DepositOrderOpenApiVo updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 更新时间（毫秒时间戳）
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "更新时间（毫秒时间戳）")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public DepositOrderOpenApiVo userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 用户ID（主账号）
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "用户ID（主账号）")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public DepositOrderOpenApiVo subUserId(String subUserId) {
    
    this.subUserId = subUserId;
    return this;
  }

   /**
   * 子用户ID
   * @return subUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "子用户ID")

  public String getSubUserId() {
    return subUserId;
  }


  public void setSubUserId(String subUserId) {
    this.subUserId = subUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositOrderOpenApiVo depositOrderOpenApiVo = (DepositOrderOpenApiVo) o;
    return Objects.equals(this.id, depositOrderOpenApiVo.id) &&
        Objects.equals(this.tokenId, depositOrderOpenApiVo.tokenId) &&
        Objects.equals(this.chainTokenId, depositOrderOpenApiVo.chainTokenId) &&
        Objects.equals(this.quantity, depositOrderOpenApiVo.quantity) &&
        Objects.equals(this.fromAddress, depositOrderOpenApiVo.fromAddress) &&
        Objects.equals(this.walletAddress, depositOrderOpenApiVo.walletAddress) &&
        Objects.equals(this.txId, depositOrderOpenApiVo.txId) &&
        Objects.equals(this.status, depositOrderOpenApiVo.status) &&
        Objects.equals(this.createdAt, depositOrderOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, depositOrderOpenApiVo.updatedAt) &&
        Objects.equals(this.userId, depositOrderOpenApiVo.userId) &&
        Objects.equals(this.subUserId, depositOrderOpenApiVo.subUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tokenId, chainTokenId, quantity, fromAddress, walletAddress, txId, status, createdAt, updatedAt, userId, subUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositOrderOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainTokenId: ").append(toIndentedString(chainTokenId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

