/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * 充值订单OpenAPI响应VO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class DepositOrderOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_ORDER_NO = "orderNo";
  @SerializedName(SERIALIZED_NAME_ORDER_NO)
  @javax.annotation.Nullable
  private String orderNo;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nullable
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nullable
  private String chainId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private String quantity;

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  @javax.annotation.Nullable
  private String fee;

  public static final String SERIALIZED_NAME_NET_AMOUNT = "netAmount";
  @SerializedName(SERIALIZED_NAME_NET_AMOUNT)
  @javax.annotation.Nullable
  private String netAmount;

  public static final String SERIALIZED_NAME_FROM_ADDRESS = "fromAddress";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS)
  @javax.annotation.Nullable
  private String fromAddress;

  public static final String SERIALIZED_NAME_WALLET_ADDRESS = "walletAddress";
  @SerializedName(SERIALIZED_NAME_WALLET_ADDRESS)
  @javax.annotation.Nullable
  private String walletAddress;

  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  @javax.annotation.Nullable
  private String txId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Integer status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  @javax.annotation.Nullable
  private String subUserId;

  public DepositOrderOpenApiVo() {
  }

  public DepositOrderOpenApiVo id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * 充值订单ID
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public DepositOrderOpenApiVo orderNo(@javax.annotation.Nullable String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

  /**
   * 订单号
   * @return orderNo
   */
  @javax.annotation.Nullable
  public String getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(@javax.annotation.Nullable String orderNo) {
    this.orderNo = orderNo;
  }


  public DepositOrderOpenApiVo tokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * 币种ID
   * @return tokenId
   */
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }


  public DepositOrderOpenApiVo chainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * 链上币种ID
   * @return chainId
   */
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
  }


  public DepositOrderOpenApiVo quantity(@javax.annotation.Nullable String quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * 充值数量
   * @return quantity
   */
  @javax.annotation.Nullable
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable String quantity) {
    this.quantity = quantity;
  }


  public DepositOrderOpenApiVo fee(@javax.annotation.Nullable String fee) {
    this.fee = fee;
    return this;
  }

  /**
   * 手续费
   * @return fee
   */
  @javax.annotation.Nullable
  public String getFee() {
    return fee;
  }

  public void setFee(@javax.annotation.Nullable String fee) {
    this.fee = fee;
  }


  public DepositOrderOpenApiVo netAmount(@javax.annotation.Nullable String netAmount) {
    this.netAmount = netAmount;
    return this;
  }

  /**
   * 净入账金额
   * @return netAmount
   */
  @javax.annotation.Nullable
  public String getNetAmount() {
    return netAmount;
  }

  public void setNetAmount(@javax.annotation.Nullable String netAmount) {
    this.netAmount = netAmount;
  }


  public DepositOrderOpenApiVo fromAddress(@javax.annotation.Nullable String fromAddress) {
    this.fromAddress = fromAddress;
    return this;
  }

  /**
   * 来源地址
   * @return fromAddress
   */
  @javax.annotation.Nullable
  public String getFromAddress() {
    return fromAddress;
  }

  public void setFromAddress(@javax.annotation.Nullable String fromAddress) {
    this.fromAddress = fromAddress;
  }


  public DepositOrderOpenApiVo walletAddress(@javax.annotation.Nullable String walletAddress) {
    this.walletAddress = walletAddress;
    return this;
  }

  /**
   * 钱包地址
   * @return walletAddress
   */
  @javax.annotation.Nullable
  public String getWalletAddress() {
    return walletAddress;
  }

  public void setWalletAddress(@javax.annotation.Nullable String walletAddress) {
    this.walletAddress = walletAddress;
  }


  public DepositOrderOpenApiVo txId(@javax.annotation.Nullable String txId) {
    this.txId = txId;
    return this;
  }

  /**
   * 交易ID（区块链交易哈希）
   * @return txId
   */
  @javax.annotation.Nullable
  public String getTxId() {
    return txId;
  }

  public void setTxId(@javax.annotation.Nullable String txId) {
    this.txId = txId;
  }


  public DepositOrderOpenApiVo status(@javax.annotation.Nullable Integer status) {
    this.status = status;
    return this;
  }

  /**
   * 充值状态： 0: 初始化 INIT; 1: 完成 已到账; 2: 处理中 充值中; 3: 失败
   * @return status
   */
  @javax.annotation.Nullable
  public Integer getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Integer status) {
    this.status = status;
  }


  public DepositOrderOpenApiVo createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * 创建时间（毫秒时间戳）
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public DepositOrderOpenApiVo updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * 更新时间（毫秒时间戳）
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public DepositOrderOpenApiVo userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * 用户ID（主账号）
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public DepositOrderOpenApiVo subUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
    return this;
  }

  /**
   * 子用户ID
   * @return subUserId
   */
  @javax.annotation.Nullable
  public String getSubUserId() {
    return subUserId;
  }

  public void setSubUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositOrderOpenApiVo depositOrderOpenApiVo = (DepositOrderOpenApiVo) o;
    return Objects.equals(this.id, depositOrderOpenApiVo.id) &&
        Objects.equals(this.orderNo, depositOrderOpenApiVo.orderNo) &&
        Objects.equals(this.tokenId, depositOrderOpenApiVo.tokenId) &&
        Objects.equals(this.chainId, depositOrderOpenApiVo.chainId) &&
        Objects.equals(this.quantity, depositOrderOpenApiVo.quantity) &&
        Objects.equals(this.fee, depositOrderOpenApiVo.fee) &&
        Objects.equals(this.netAmount, depositOrderOpenApiVo.netAmount) &&
        Objects.equals(this.fromAddress, depositOrderOpenApiVo.fromAddress) &&
        Objects.equals(this.walletAddress, depositOrderOpenApiVo.walletAddress) &&
        Objects.equals(this.txId, depositOrderOpenApiVo.txId) &&
        Objects.equals(this.status, depositOrderOpenApiVo.status) &&
        Objects.equals(this.createdAt, depositOrderOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, depositOrderOpenApiVo.updatedAt) &&
        Objects.equals(this.userId, depositOrderOpenApiVo.userId) &&
        Objects.equals(this.subUserId, depositOrderOpenApiVo.subUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderNo, tokenId, chainId, quantity, fee, netAmount, fromAddress, walletAddress, txId, status, createdAt, updatedAt, userId, subUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositOrderOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("orderNo");
    openapiFields.add("tokenId");
    openapiFields.add("chainId");
    openapiFields.add("quantity");
    openapiFields.add("fee");
    openapiFields.add("netAmount");
    openapiFields.add("fromAddress");
    openapiFields.add("walletAddress");
    openapiFields.add("txId");
    openapiFields.add("status");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("userId");
    openapiFields.add("subUserId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DepositOrderOpenApiVo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DepositOrderOpenApiVo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DepositOrderOpenApiVo is not found in the empty JSON string", DepositOrderOpenApiVo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DepositOrderOpenApiVo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DepositOrderOpenApiVo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("orderNo") != null && !jsonObj.get("orderNo").isJsonNull()) && !jsonObj.get("orderNo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderNo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderNo").toString()));
      }
      if ((jsonObj.get("tokenId") != null && !jsonObj.get("tokenId").isJsonNull()) && !jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull()) && !jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
      if ((jsonObj.get("quantity") != null && !jsonObj.get("quantity").isJsonNull()) && !jsonObj.get("quantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `quantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quantity").toString()));
      }
      if ((jsonObj.get("fee") != null && !jsonObj.get("fee").isJsonNull()) && !jsonObj.get("fee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fee").toString()));
      }
      if ((jsonObj.get("netAmount") != null && !jsonObj.get("netAmount").isJsonNull()) && !jsonObj.get("netAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `netAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("netAmount").toString()));
      }
      if ((jsonObj.get("fromAddress") != null && !jsonObj.get("fromAddress").isJsonNull()) && !jsonObj.get("fromAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fromAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromAddress").toString()));
      }
      if ((jsonObj.get("walletAddress") != null && !jsonObj.get("walletAddress").isJsonNull()) && !jsonObj.get("walletAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `walletAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("walletAddress").toString()));
      }
      if ((jsonObj.get("txId") != null && !jsonObj.get("txId").isJsonNull()) && !jsonObj.get("txId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `txId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("txId").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("subUserId") != null && !jsonObj.get("subUserId").isJsonNull()) && !jsonObj.get("subUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subUserId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DepositOrderOpenApiVo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DepositOrderOpenApiVo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DepositOrderOpenApiVo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DepositOrderOpenApiVo.class));

       return (TypeAdapter<T>) new TypeAdapter<DepositOrderOpenApiVo>() {
           @Override
           public void write(JsonWriter out, DepositOrderOpenApiVo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DepositOrderOpenApiVo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DepositOrderOpenApiVo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DepositOrderOpenApiVo
   * @throws IOException if the JSON string is invalid with respect to DepositOrderOpenApiVo
   */
  public static DepositOrderOpenApiVo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DepositOrderOpenApiVo.class);
  }

  /**
   * Convert an instance of DepositOrderOpenApiVo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

