/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 获取子用户充值地址请求DTO
 */
@ApiModel(description = "获取子用户充值地址请求DTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-13T11:09:51.307434+08:00[Asia/Shanghai]")
public class GetDepositAddressRequest {
  public static final String SERIALIZED_NAME_CLIENT_SUB_USER_ID = "clientSubUserId";
  @SerializedName(SERIALIZED_NAME_CLIENT_SUB_USER_ID)
  private String clientSubUserId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;


  public GetDepositAddressRequest clientSubUserId(String clientSubUserId) {
    
    this.clientSubUserId = clientSubUserId;
    return this;
  }

   /**
   * 客户子用户唯一标识
   * @return clientSubUserId
  **/
  @NotNull
 @Size(min=1,max=64)  @ApiModelProperty(required = true, value = "客户子用户唯一标识")

  public String getClientSubUserId() {
    return clientSubUserId;
  }


  public void setClientSubUserId(String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
  }


  public GetDepositAddressRequest tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * 币种ID
   * @return tokenId
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "币种ID")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDepositAddressRequest getDepositAddressRequest = (GetDepositAddressRequest) o;
    return Objects.equals(this.clientSubUserId, getDepositAddressRequest.clientSubUserId) &&
        Objects.equals(this.tokenId, getDepositAddressRequest.tokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientSubUserId, tokenId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDepositAddressRequest {\n");
    sb.append("    clientSubUserId: ").append(toIndentedString(clientSubUserId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

