/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * 获取子用户充值地址请求DTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class GetDepositAddressRequest {
  public static final String SERIALIZED_NAME_CLIENT_SUB_USER_ID = "clientSubUserId";
  @SerializedName(SERIALIZED_NAME_CLIENT_SUB_USER_ID)
  @javax.annotation.Nonnull
  private String clientSubUserId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nonnull
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nonnull
  private String chainId;

  public GetDepositAddressRequest() {
  }

  public GetDepositAddressRequest clientSubUserId(@javax.annotation.Nonnull String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
    return this;
  }

  /**
   * 客户子用户唯一标识
   * @return clientSubUserId
   */
  @javax.annotation.Nonnull
  public String getClientSubUserId() {
    return clientSubUserId;
  }

  public void setClientSubUserId(@javax.annotation.Nonnull String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
  }


  public GetDepositAddressRequest tokenId(@javax.annotation.Nonnull String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * 币种ID
   * @return tokenId
   */
  @javax.annotation.Nonnull
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nonnull String tokenId) {
    this.tokenId = tokenId;
  }


  public GetDepositAddressRequest chainId(@javax.annotation.Nonnull String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * 链ID
   * @return chainId
   */
  @javax.annotation.Nonnull
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nonnull String chainId) {
    this.chainId = chainId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDepositAddressRequest getDepositAddressRequest = (GetDepositAddressRequest) o;
    return Objects.equals(this.clientSubUserId, getDepositAddressRequest.clientSubUserId) &&
        Objects.equals(this.tokenId, getDepositAddressRequest.tokenId) &&
        Objects.equals(this.chainId, getDepositAddressRequest.chainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientSubUserId, tokenId, chainId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDepositAddressRequest {\n");
    sb.append("    clientSubUserId: ").append(toIndentedString(clientSubUserId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("clientSubUserId");
    openapiFields.add("tokenId");
    openapiFields.add("chainId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("clientSubUserId");
    openapiRequiredFields.add("tokenId");
    openapiRequiredFields.add("chainId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetDepositAddressRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetDepositAddressRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetDepositAddressRequest is not found in the empty JSON string", GetDepositAddressRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetDepositAddressRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetDepositAddressRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetDepositAddressRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("clientSubUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientSubUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientSubUserId").toString()));
      }
      if (!jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if (!jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetDepositAddressRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetDepositAddressRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetDepositAddressRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetDepositAddressRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GetDepositAddressRequest>() {
           @Override
           public void write(JsonWriter out, GetDepositAddressRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetDepositAddressRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetDepositAddressRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetDepositAddressRequest
   * @throws IOException if the JSON string is invalid with respect to GetDepositAddressRequest
   */
  public static GetDepositAddressRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetDepositAddressRequest.class);
  }

  /**
   * Convert an instance of GetDepositAddressRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

