/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 查询充值订单请求DTO
 */
@ApiModel(description = "查询充值订单请求DTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T15:36:39.334120+08:00[Asia/Shanghai]")
public class QueryDepositOrderRequest {
  public static final String SERIALIZED_NAME_SUB_UID = "subUid";
  @SerializedName(SERIALIZED_NAME_SUB_UID)
  private String subUid;

  public static final String SERIALIZED_NAME_WALLET_ADDRESS = "walletAddress";
  @SerializedName(SERIALIZED_NAME_WALLET_ADDRESS)
  private String walletAddress;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private String startTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private String endTime;

  public static final String SERIALIZED_NAME_PAGE_NO = "pageNo";
  @SerializedName(SERIALIZED_NAME_PAGE_NO)
  private Integer pageNo;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  private Integer pageSize;


  public QueryDepositOrderRequest subUid(String subUid) {
    
    this.subUid = subUid;
    return this;
  }

   /**
   * 子用户ID
   * @return subUid
  **/
  @ApiModelProperty(required = true, value = "子用户ID")

  public String getSubUid() {
    return subUid;
  }


  public void setSubUid(String subUid) {
    this.subUid = subUid;
  }


  public QueryDepositOrderRequest walletAddress(String walletAddress) {
    
    this.walletAddress = walletAddress;
    return this;
  }

   /**
   * 钱包地址
   * @return walletAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "钱包地址")

  public String getWalletAddress() {
    return walletAddress;
  }


  public void setWalletAddress(String walletAddress) {
    this.walletAddress = walletAddress;
  }


  public QueryDepositOrderRequest tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * 币种ID
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "币种ID")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public QueryDepositOrderRequest startTime(String startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * 开始时间（毫秒时间戳）
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "开始时间（毫秒时间戳）")

  public String getStartTime() {
    return startTime;
  }


  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }


  public QueryDepositOrderRequest endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * 结束时间（毫秒时间戳）
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "结束时间（毫秒时间戳）")

  public String getEndTime() {
    return endTime;
  }


  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public QueryDepositOrderRequest pageNo(Integer pageNo) {
    
    this.pageNo = pageNo;
    return this;
  }

   /**
   * 页码，从1开始
   * @return pageNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "页码，从1开始")

  public Integer getPageNo() {
    return pageNo;
  }


  public void setPageNo(Integer pageNo) {
    this.pageNo = pageNo;
  }


  public QueryDepositOrderRequest pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 每页大小，范围1-100
   * minimum: 1
   * maximum: 100
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "每页大小，范围1-100")

  public Integer getPageSize() {
    return pageSize;
  }


  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryDepositOrderRequest queryDepositOrderRequest = (QueryDepositOrderRequest) o;
    return Objects.equals(this.subUid, queryDepositOrderRequest.subUid) &&
        Objects.equals(this.walletAddress, queryDepositOrderRequest.walletAddress) &&
        Objects.equals(this.tokenId, queryDepositOrderRequest.tokenId) &&
        Objects.equals(this.startTime, queryDepositOrderRequest.startTime) &&
        Objects.equals(this.endTime, queryDepositOrderRequest.endTime) &&
        Objects.equals(this.pageNo, queryDepositOrderRequest.pageNo) &&
        Objects.equals(this.pageSize, queryDepositOrderRequest.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subUid, walletAddress, tokenId, startTime, endTime, pageNo, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryDepositOrderRequest {\n");
    sb.append("    subUid: ").append(toIndentedString(subUid)).append("\n");
    sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    pageNo: ").append(toIndentedString(pageNo)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

