/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * 查询充值订单请求DTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class QueryDepositOrderRequest {
  public static final String SERIALIZED_NAME_SUB_UID = "subUid";
  @SerializedName(SERIALIZED_NAME_SUB_UID)
  @javax.annotation.Nullable
  private String subUid;

  public static final String SERIALIZED_NAME_CLIENT_SUB_USER_ID = "clientSubUserId";
  @SerializedName(SERIALIZED_NAME_CLIENT_SUB_USER_ID)
  @javax.annotation.Nullable
  private String clientSubUserId;

  public static final String SERIALIZED_NAME_WALLET_ADDRESS = "walletAddress";
  @SerializedName(SERIALIZED_NAME_WALLET_ADDRESS)
  @javax.annotation.Nullable
  private String walletAddress;

  public static final String SERIALIZED_NAME_ORDER_NO = "orderNo";
  @SerializedName(SERIALIZED_NAME_ORDER_NO)
  @javax.annotation.Nullable
  private String orderNo;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nullable
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nullable
  private String chainId;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  @javax.annotation.Nullable
  private String startTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  @javax.annotation.Nullable
  private String endTime;

  public static final String SERIALIZED_NAME_PAGE_NO = "pageNo";
  @SerializedName(SERIALIZED_NAME_PAGE_NO)
  @javax.annotation.Nullable
  private Integer pageNo;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Integer pageSize;

  public static final String SERIALIZED_NAME_VALID_SUB_USER_IDENTIFIER = "validSubUserIdentifier";
  @SerializedName(SERIALIZED_NAME_VALID_SUB_USER_IDENTIFIER)
  @javax.annotation.Nullable
  private Boolean validSubUserIdentifier;

  public QueryDepositOrderRequest() {
  }

  public QueryDepositOrderRequest subUid(@javax.annotation.Nullable String subUid) {
    this.subUid = subUid;
    return this;
  }

  /**
   * 子用户ID
   * @return subUid
   */
  @javax.annotation.Nullable
  public String getSubUid() {
    return subUid;
  }

  public void setSubUid(@javax.annotation.Nullable String subUid) {
    this.subUid = subUid;
  }


  public QueryDepositOrderRequest clientSubUserId(@javax.annotation.Nullable String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
    return this;
  }

  /**
   * 客户子用户唯一标识
   * @return clientSubUserId
   */
  @javax.annotation.Nullable
  public String getClientSubUserId() {
    return clientSubUserId;
  }

  public void setClientSubUserId(@javax.annotation.Nullable String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
  }


  public QueryDepositOrderRequest walletAddress(@javax.annotation.Nullable String walletAddress) {
    this.walletAddress = walletAddress;
    return this;
  }

  /**
   * 钱包地址
   * @return walletAddress
   */
  @javax.annotation.Nullable
  public String getWalletAddress() {
    return walletAddress;
  }

  public void setWalletAddress(@javax.annotation.Nullable String walletAddress) {
    this.walletAddress = walletAddress;
  }


  public QueryDepositOrderRequest orderNo(@javax.annotation.Nullable String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

  /**
   * 订单号
   * @return orderNo
   */
  @javax.annotation.Nullable
  public String getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(@javax.annotation.Nullable String orderNo) {
    this.orderNo = orderNo;
  }


  public QueryDepositOrderRequest tokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * 币种ID
   * @return tokenId
   */
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }


  public QueryDepositOrderRequest chainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * 链ID
   * @return chainId
   */
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
  }


  public QueryDepositOrderRequest startTime(@javax.annotation.Nullable String startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * 开始时间（毫秒时间戳）
   * @return startTime
   */
  @javax.annotation.Nullable
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(@javax.annotation.Nullable String startTime) {
    this.startTime = startTime;
  }


  public QueryDepositOrderRequest endTime(@javax.annotation.Nullable String endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * 结束时间（毫秒时间戳）
   * @return endTime
   */
  @javax.annotation.Nullable
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(@javax.annotation.Nullable String endTime) {
    this.endTime = endTime;
  }


  public QueryDepositOrderRequest pageNo(@javax.annotation.Nullable Integer pageNo) {
    this.pageNo = pageNo;
    return this;
  }

  /**
   * 页码，从1开始
   * @return pageNo
   */
  @javax.annotation.Nullable
  public Integer getPageNo() {
    return pageNo;
  }

  public void setPageNo(@javax.annotation.Nullable Integer pageNo) {
    this.pageNo = pageNo;
  }


  public QueryDepositOrderRequest pageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * 每页大小，范围1-100
   * minimum: 1
   * maximum: 100
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }


  public QueryDepositOrderRequest validSubUserIdentifier(@javax.annotation.Nullable Boolean validSubUserIdentifier) {
    this.validSubUserIdentifier = validSubUserIdentifier;
    return this;
  }

  /**
   * Get validSubUserIdentifier
   * @return validSubUserIdentifier
   */
  @javax.annotation.Nullable
  public Boolean getValidSubUserIdentifier() {
    return validSubUserIdentifier;
  }

  public void setValidSubUserIdentifier(@javax.annotation.Nullable Boolean validSubUserIdentifier) {
    this.validSubUserIdentifier = validSubUserIdentifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryDepositOrderRequest queryDepositOrderRequest = (QueryDepositOrderRequest) o;
    return Objects.equals(this.subUid, queryDepositOrderRequest.subUid) &&
        Objects.equals(this.clientSubUserId, queryDepositOrderRequest.clientSubUserId) &&
        Objects.equals(this.walletAddress, queryDepositOrderRequest.walletAddress) &&
        Objects.equals(this.orderNo, queryDepositOrderRequest.orderNo) &&
        Objects.equals(this.tokenId, queryDepositOrderRequest.tokenId) &&
        Objects.equals(this.chainId, queryDepositOrderRequest.chainId) &&
        Objects.equals(this.startTime, queryDepositOrderRequest.startTime) &&
        Objects.equals(this.endTime, queryDepositOrderRequest.endTime) &&
        Objects.equals(this.pageNo, queryDepositOrderRequest.pageNo) &&
        Objects.equals(this.pageSize, queryDepositOrderRequest.pageSize) &&
        Objects.equals(this.validSubUserIdentifier, queryDepositOrderRequest.validSubUserIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subUid, clientSubUserId, walletAddress, orderNo, tokenId, chainId, startTime, endTime, pageNo, pageSize, validSubUserIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryDepositOrderRequest {\n");
    sb.append("    subUid: ").append(toIndentedString(subUid)).append("\n");
    sb.append("    clientSubUserId: ").append(toIndentedString(clientSubUserId)).append("\n");
    sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    pageNo: ").append(toIndentedString(pageNo)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    validSubUserIdentifier: ").append(toIndentedString(validSubUserIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subUid");
    openapiFields.add("clientSubUserId");
    openapiFields.add("walletAddress");
    openapiFields.add("orderNo");
    openapiFields.add("tokenId");
    openapiFields.add("chainId");
    openapiFields.add("startTime");
    openapiFields.add("endTime");
    openapiFields.add("pageNo");
    openapiFields.add("pageSize");
    openapiFields.add("validSubUserIdentifier");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryDepositOrderRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryDepositOrderRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QueryDepositOrderRequest is not found in the empty JSON string", QueryDepositOrderRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QueryDepositOrderRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QueryDepositOrderRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("subUid") != null && !jsonObj.get("subUid").isJsonNull()) && !jsonObj.get("subUid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subUid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subUid").toString()));
      }
      if ((jsonObj.get("clientSubUserId") != null && !jsonObj.get("clientSubUserId").isJsonNull()) && !jsonObj.get("clientSubUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientSubUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientSubUserId").toString()));
      }
      if ((jsonObj.get("walletAddress") != null && !jsonObj.get("walletAddress").isJsonNull()) && !jsonObj.get("walletAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `walletAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("walletAddress").toString()));
      }
      if ((jsonObj.get("orderNo") != null && !jsonObj.get("orderNo").isJsonNull()) && !jsonObj.get("orderNo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderNo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderNo").toString()));
      }
      if ((jsonObj.get("tokenId") != null && !jsonObj.get("tokenId").isJsonNull()) && !jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull()) && !jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
      if ((jsonObj.get("startTime") != null && !jsonObj.get("startTime").isJsonNull()) && !jsonObj.get("startTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startTime").toString()));
      }
      if ((jsonObj.get("endTime") != null && !jsonObj.get("endTime").isJsonNull()) && !jsonObj.get("endTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endTime").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryDepositOrderRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryDepositOrderRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryDepositOrderRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryDepositOrderRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryDepositOrderRequest>() {
           @Override
           public void write(JsonWriter out, QueryDepositOrderRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryDepositOrderRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryDepositOrderRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryDepositOrderRequest
   * @throws IOException if the JSON string is invalid with respect to QueryDepositOrderRequest
   */
  public static QueryDepositOrderRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryDepositOrderRequest.class);
  }

  /**
   * Convert an instance of QueryDepositOrderRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

