/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 查询提币订单请求DTO
 */
@ApiModel(description = "查询提币订单请求DTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-13T11:09:51.307434+08:00[Asia/Shanghai]")
public class QueryWithdrawalOrderRequest {
  public static final String SERIALIZED_NAME_SUB_UID = "subUid";
  @SerializedName(SERIALIZED_NAME_SUB_UID)
  private String subUid;

  public static final String SERIALIZED_NAME_CLIENT_SUB_USER_ID = "clientSubUserId";
  @SerializedName(SERIALIZED_NAME_CLIENT_SUB_USER_ID)
  private String clientSubUserId;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID = "clientWithdrawalId";
  @SerializedName(SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID)
  private String clientWithdrawalId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private String startTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private String endTime;

  public static final String SERIALIZED_NAME_PAGE_NO = "pageNo";
  @SerializedName(SERIALIZED_NAME_PAGE_NO)
  private Integer pageNo;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  private Integer pageSize;


  public QueryWithdrawalOrderRequest subUid(String subUid) {
    
    this.subUid = subUid;
    return this;
  }

   /**
   * 子用户ID
   * @return subUid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "子用户ID")

  public String getSubUid() {
    return subUid;
  }


  public void setSubUid(String subUid) {
    this.subUid = subUid;
  }


  public QueryWithdrawalOrderRequest clientSubUserId(String clientSubUserId) {
    
    this.clientSubUserId = clientSubUserId;
    return this;
  }

   /**
   * 客户子用户唯一标识
   * @return clientSubUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "客户子用户唯一标识")

  public String getClientSubUserId() {
    return clientSubUserId;
  }


  public void setClientSubUserId(String clientSubUserId) {
    this.clientSubUserId = clientSubUserId;
  }


  public QueryWithdrawalOrderRequest address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * 提币地址
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "提币地址")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public QueryWithdrawalOrderRequest clientWithdrawalId(String clientWithdrawalId) {
    
    this.clientWithdrawalId = clientWithdrawalId;
    return this;
  }

   /**
   * 客户端提币订单ID
   * @return clientWithdrawalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "客户端提币订单ID")

  public String getClientWithdrawalId() {
    return clientWithdrawalId;
  }


  public void setClientWithdrawalId(String clientWithdrawalId) {
    this.clientWithdrawalId = clientWithdrawalId;
  }


  public QueryWithdrawalOrderRequest tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * 币种ID
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "币种ID")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public QueryWithdrawalOrderRequest txId(String txId) {
    
    this.txId = txId;
    return this;
  }

   /**
   * 交易ID（区块链交易哈希）
   * @return txId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "交易ID（区块链交易哈希）")

  public String getTxId() {
    return txId;
  }


  public void setTxId(String txId) {
    this.txId = txId;
  }


  public QueryWithdrawalOrderRequest startTime(String startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * 开始时间（毫秒时间戳）
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "开始时间（毫秒时间戳）")

  public String getStartTime() {
    return startTime;
  }


  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }


  public QueryWithdrawalOrderRequest endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * 结束时间（毫秒时间戳）
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "结束时间（毫秒时间戳）")

  public String getEndTime() {
    return endTime;
  }


  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  public QueryWithdrawalOrderRequest pageNo(Integer pageNo) {
    
    this.pageNo = pageNo;
    return this;
  }

   /**
   * 页码，从1开始
   * @return pageNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "页码，从1开始")

  public Integer getPageNo() {
    return pageNo;
  }


  public void setPageNo(Integer pageNo) {
    this.pageNo = pageNo;
  }


  public QueryWithdrawalOrderRequest pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 每页大小，范围1-100
   * minimum: 1
   * maximum: 100
   * @return pageSize
  **/
  @javax.annotation.Nullable
 @Min(1) @Max(100)  @ApiModelProperty(value = "每页大小，范围1-100")

  public Integer getPageSize() {
    return pageSize;
  }


  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryWithdrawalOrderRequest queryWithdrawalOrderRequest = (QueryWithdrawalOrderRequest) o;
    return Objects.equals(this.subUid, queryWithdrawalOrderRequest.subUid) &&
        Objects.equals(this.clientSubUserId, queryWithdrawalOrderRequest.clientSubUserId) &&
        Objects.equals(this.address, queryWithdrawalOrderRequest.address) &&
        Objects.equals(this.clientWithdrawalId, queryWithdrawalOrderRequest.clientWithdrawalId) &&
        Objects.equals(this.tokenId, queryWithdrawalOrderRequest.tokenId) &&
        Objects.equals(this.txId, queryWithdrawalOrderRequest.txId) &&
        Objects.equals(this.startTime, queryWithdrawalOrderRequest.startTime) &&
        Objects.equals(this.endTime, queryWithdrawalOrderRequest.endTime) &&
        Objects.equals(this.pageNo, queryWithdrawalOrderRequest.pageNo) &&
        Objects.equals(this.pageSize, queryWithdrawalOrderRequest.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subUid, clientSubUserId, address, clientWithdrawalId, tokenId, txId, startTime, endTime, pageNo, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryWithdrawalOrderRequest {\n");
    sb.append("    subUid: ").append(toIndentedString(subUid)).append("\n");
    sb.append("    clientSubUserId: ").append(toIndentedString(clientSubUserId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    clientWithdrawalId: ").append(toIndentedString(clientWithdrawalId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    pageNo: ").append(toIndentedString(pageNo)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

