/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 企业子用户钱包地址实体类  用于存储和管理子用户的钱包地址信息  对应数据库表：tb_sub_wallet_address
 */
@ApiModel(description = "企业子用户钱包地址实体类  用于存储和管理子用户的钱包地址信息  对应数据库表：tb_sub_wallet_address")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-10T15:36:39.334120+08:00[Asia/Shanghai]")
public class SubWalletAddressOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  private String subUserId;


  public SubWalletAddressOpenApiVo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 主键ID
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "主键ID")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public SubWalletAddressOpenApiVo userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 用户ID  主账号用户的标识符
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "用户ID  主账号用户的标识符")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public SubWalletAddressOpenApiVo tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * 币种ID  例如：TBSC_BNB、TBSC_USDT等
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "币种ID  例如：TBSC_BNB、TBSC_USDT等")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public SubWalletAddressOpenApiVo address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * 钱包地址  区块链上的钱包地址，用于接收充值
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "钱包地址  区块链上的钱包地址，用于接收充值")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public SubWalletAddressOpenApiVo createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 创建时间  记录创建的时间戳（毫秒）
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "创建时间  记录创建的时间戳（毫秒）")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public SubWalletAddressOpenApiVo updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 更新时间  记录最后更新的时间戳（毫秒）
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "更新时间  记录最后更新的时间戳（毫秒）")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SubWalletAddressOpenApiVo tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * 标签  某些币种（如XRP、XLM等）需要的额外标识符
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标签  某些币种（如XRP、XLM等）需要的额外标识符")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  public SubWalletAddressOpenApiVo subUserId(String subUserId) {
    
    this.subUserId = subUserId;
    return this;
  }

   /**
   * 子用户ID  企业-子用户的ID，标识具体的子账号
   * @return subUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "子用户ID  企业-子用户的ID，标识具体的子账号")

  public String getSubUserId() {
    return subUserId;
  }


  public void setSubUserId(String subUserId) {
    this.subUserId = subUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubWalletAddressOpenApiVo subWalletAddressOpenApiVo = (SubWalletAddressOpenApiVo) o;
    return Objects.equals(this.id, subWalletAddressOpenApiVo.id) &&
        Objects.equals(this.userId, subWalletAddressOpenApiVo.userId) &&
        Objects.equals(this.tokenId, subWalletAddressOpenApiVo.tokenId) &&
        Objects.equals(this.address, subWalletAddressOpenApiVo.address) &&
        Objects.equals(this.createdAt, subWalletAddressOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, subWalletAddressOpenApiVo.updatedAt) &&
        Objects.equals(this.tag, subWalletAddressOpenApiVo.tag) &&
        Objects.equals(this.subUserId, subWalletAddressOpenApiVo.subUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, tokenId, address, createdAt, updatedAt, tag, subUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubWalletAddressOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

