/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * 企业子用户钱包地址实体类  用于存储和管理子用户的钱包地址信息  对应数据库表：tb_sub_wallet_address
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class SubWalletAddressOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nullable
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nullable
  private String chainId;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  @javax.annotation.Nullable
  private String tag;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  @javax.annotation.Nullable
  private String subUserId;

  public SubWalletAddressOpenApiVo() {
  }

  public SubWalletAddressOpenApiVo id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * 主键ID
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SubWalletAddressOpenApiVo userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * 用户ID  主账号用户的标识符
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public SubWalletAddressOpenApiVo tokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * 币种ID  例如：USDT，USDC等
   * @return tokenId
   */
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }


  public SubWalletAddressOpenApiVo chainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * chainId  例如：BNB，TRON
   * @return chainId
   */
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
  }


  public SubWalletAddressOpenApiVo address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * 钱包地址  区块链上的钱包地址，用于接收充值
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public SubWalletAddressOpenApiVo createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * 创建时间  记录创建的时间戳（毫秒）
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public SubWalletAddressOpenApiVo updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * 更新时间  记录最后更新的时间戳（毫秒）
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SubWalletAddressOpenApiVo tag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * 标签  某些币种（如XRP、XLM等）需要的额外标识符
   * @return tag
   */
  @javax.annotation.Nullable
  public String getTag() {
    return tag;
  }

  public void setTag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public SubWalletAddressOpenApiVo subUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
    return this;
  }

  /**
   * 子用户ID  企业-子用户的ID，标识具体的子账号
   * @return subUserId
   */
  @javax.annotation.Nullable
  public String getSubUserId() {
    return subUserId;
  }

  public void setSubUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubWalletAddressOpenApiVo subWalletAddressOpenApiVo = (SubWalletAddressOpenApiVo) o;
    return Objects.equals(this.id, subWalletAddressOpenApiVo.id) &&
        Objects.equals(this.userId, subWalletAddressOpenApiVo.userId) &&
        Objects.equals(this.tokenId, subWalletAddressOpenApiVo.tokenId) &&
        Objects.equals(this.chainId, subWalletAddressOpenApiVo.chainId) &&
        Objects.equals(this.address, subWalletAddressOpenApiVo.address) &&
        Objects.equals(this.createdAt, subWalletAddressOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, subWalletAddressOpenApiVo.updatedAt) &&
        Objects.equals(this.tag, subWalletAddressOpenApiVo.tag) &&
        Objects.equals(this.subUserId, subWalletAddressOpenApiVo.subUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, tokenId, chainId, address, createdAt, updatedAt, tag, subUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubWalletAddressOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("userId");
    openapiFields.add("tokenId");
    openapiFields.add("chainId");
    openapiFields.add("address");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("tag");
    openapiFields.add("subUserId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubWalletAddressOpenApiVo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubWalletAddressOpenApiVo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubWalletAddressOpenApiVo is not found in the empty JSON string", SubWalletAddressOpenApiVo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubWalletAddressOpenApiVo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubWalletAddressOpenApiVo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("tokenId") != null && !jsonObj.get("tokenId").isJsonNull()) && !jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull()) && !jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) && !jsonObj.get("tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag").toString()));
      }
      if ((jsonObj.get("subUserId") != null && !jsonObj.get("subUserId").isJsonNull()) && !jsonObj.get("subUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subUserId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubWalletAddressOpenApiVo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubWalletAddressOpenApiVo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubWalletAddressOpenApiVo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubWalletAddressOpenApiVo.class));

       return (TypeAdapter<T>) new TypeAdapter<SubWalletAddressOpenApiVo>() {
           @Override
           public void write(JsonWriter out, SubWalletAddressOpenApiVo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubWalletAddressOpenApiVo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubWalletAddressOpenApiVo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubWalletAddressOpenApiVo
   * @throws IOException if the JSON string is invalid with respect to SubWalletAddressOpenApiVo
   */
  public static SubWalletAddressOpenApiVo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubWalletAddressOpenApiVo.class);
  }

  /**
   * Convert an instance of SubWalletAddressOpenApiVo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

