/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * token 基本配置表
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class Token {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nullable
  private String tokenId;

  public static final String SERIALIZED_NAME_TOKEN_NAME = "tokenName";
  @SerializedName(SERIALIZED_NAME_TOKEN_NAME)
  @javax.annotation.Nullable
  private String tokenName;

  public static final String SERIALIZED_NAME_TOKEN_FULL_NAME = "tokenFullName";
  @SerializedName(SERIALIZED_NAME_TOKEN_FULL_NAME)
  @javax.annotation.Nullable
  private String tokenFullName;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nullable
  private String chainId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_ICON = "icon";
  @SerializedName(SERIALIZED_NAME_ICON)
  @javax.annotation.Nullable
  private String icon;

  public static final String SERIALIZED_NAME_PROTOCOL_NAME = "protocolName";
  @SerializedName(SERIALIZED_NAME_PROTOCOL_NAME)
  @javax.annotation.Nullable
  private String protocolName;

  public static final String SERIALIZED_NAME_CHAIN_NAME = "chainName";
  @SerializedName(SERIALIZED_NAME_CHAIN_NAME)
  @javax.annotation.Nullable
  private String chainName;

  public static final String SERIALIZED_NAME_CHAIN_ICON = "chainIcon";
  @SerializedName(SERIALIZED_NAME_CHAIN_ICON)
  @javax.annotation.Nullable
  private String chainIcon;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private Integer status;

  public static final String SERIALIZED_NAME_ALLOW_DEPOSIT = "allowDeposit";
  @SerializedName(SERIALIZED_NAME_ALLOW_DEPOSIT)
  @javax.annotation.Nullable
  private Integer allowDeposit;

  public static final String SERIALIZED_NAME_ALLOW_WITHDRAW = "allowWithdraw";
  @SerializedName(SERIALIZED_NAME_ALLOW_WITHDRAW)
  @javax.annotation.Nullable
  private Integer allowWithdraw;

  public static final String SERIALIZED_NAME_DEPOSIT_MIN_QUANTITY = "depositMinQuantity";
  @SerializedName(SERIALIZED_NAME_DEPOSIT_MIN_QUANTITY)
  @javax.annotation.Nullable
  private String depositMinQuantity;

  public static final String SERIALIZED_NAME_WITHDRAW_MIN_QUANTITY = "withdrawMinQuantity";
  @SerializedName(SERIALIZED_NAME_WITHDRAW_MIN_QUANTITY)
  @javax.annotation.Nullable
  private String withdrawMinQuantity;

  public static final String SERIALIZED_NAME_WITHDRAW_MAX_DAY_QUANTITY = "withdrawMaxDayQuantity";
  @SerializedName(SERIALIZED_NAME_WITHDRAW_MAX_DAY_QUANTITY)
  @javax.annotation.Nullable
  private String withdrawMaxDayQuantity;

  public static final String SERIALIZED_NAME_DEPOSIT_CHARGES = "depositCharges";
  @SerializedName(SERIALIZED_NAME_DEPOSIT_CHARGES)
  @javax.annotation.Nullable
  private String depositCharges;

  public static final String SERIALIZED_NAME_DEPOSIT_CHARGES_MIN_AMOUNT = "depositChargesMinAmount";
  @SerializedName(SERIALIZED_NAME_DEPOSIT_CHARGES_MIN_AMOUNT)
  @javax.annotation.Nullable
  private String depositChargesMinAmount;

  public static final String SERIALIZED_NAME_WITHDRAWAL_CHARGES_MIN_AMOUNT = "withdrawalChargesMinAmount";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_CHARGES_MIN_AMOUNT)
  @javax.annotation.Nullable
  private String withdrawalChargesMinAmount;

  public static final String SERIALIZED_NAME_WITHDRAW_CHARGE_VALUE = "withdrawChargeValue";
  @SerializedName(SERIALIZED_NAME_WITHDRAW_CHARGE_VALUE)
  @javax.annotation.Nullable
  private String withdrawChargeValue;

  public Token() {
  }

  public Token id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Token tokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * 不用数字,\&quot;USDT\&quot;
   * @return tokenId
   */
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }


  public Token tokenName(@javax.annotation.Nullable String tokenName) {
    this.tokenName = tokenName;
    return this;
  }

  /**
   * show name, can rename
   * @return tokenName
   */
  @javax.annotation.Nullable
  public String getTokenName() {
    return tokenName;
  }

  public void setTokenName(@javax.annotation.Nullable String tokenName) {
    this.tokenName = tokenName;
  }


  public Token tokenFullName(@javax.annotation.Nullable String tokenFullName) {
    this.tokenFullName = tokenFullName;
    return this;
  }

  /**
   * full name
   * @return tokenFullName
   */
  @javax.annotation.Nullable
  public String getTokenFullName() {
    return tokenFullName;
  }

  public void setTokenFullName(@javax.annotation.Nullable String tokenFullName) {
    this.tokenFullName = tokenFullName;
  }


  public Token chainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * 链tokenID,\&quot;TRON\&quot;
   * @return chainId
   */
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
  }


  public Token createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public Token updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Token icon(@javax.annotation.Nullable String icon) {
    this.icon = icon;
    return this;
  }

  /**
   * token icon
   * @return icon
   */
  @javax.annotation.Nullable
  public String getIcon() {
    return icon;
  }

  public void setIcon(@javax.annotation.Nullable String icon) {
    this.icon = icon;
  }


  public Token protocolName(@javax.annotation.Nullable String protocolName) {
    this.protocolName = protocolName;
    return this;
  }

  /**
   * 链协议名称
   * @return protocolName
   */
  @javax.annotation.Nullable
  public String getProtocolName() {
    return protocolName;
  }

  public void setProtocolName(@javax.annotation.Nullable String protocolName) {
    this.protocolName = protocolName;
  }


  public Token chainName(@javax.annotation.Nullable String chainName) {
    this.chainName = chainName;
    return this;
  }

  /**
   * 链名称
   * @return chainName
   */
  @javax.annotation.Nullable
  public String getChainName() {
    return chainName;
  }

  public void setChainName(@javax.annotation.Nullable String chainName) {
    this.chainName = chainName;
  }


  public Token chainIcon(@javax.annotation.Nullable String chainIcon) {
    this.chainIcon = chainIcon;
    return this;
  }

  /**
   * chain icon
   * @return chainIcon
   */
  @javax.annotation.Nullable
  public String getChainIcon() {
    return chainIcon;
  }

  public void setChainIcon(@javax.annotation.Nullable String chainIcon) {
    this.chainIcon = chainIcon;
  }


  public Token status(@javax.annotation.Nullable Integer status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public Integer getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable Integer status) {
    this.status = status;
  }


  public Token allowDeposit(@javax.annotation.Nullable Integer allowDeposit) {
    this.allowDeposit = allowDeposit;
    return this;
  }

  /**
   * 1允许充币，0禁止
   * @return allowDeposit
   */
  @javax.annotation.Nullable
  public Integer getAllowDeposit() {
    return allowDeposit;
  }

  public void setAllowDeposit(@javax.annotation.Nullable Integer allowDeposit) {
    this.allowDeposit = allowDeposit;
  }


  public Token allowWithdraw(@javax.annotation.Nullable Integer allowWithdraw) {
    this.allowWithdraw = allowWithdraw;
    return this;
  }

  /**
   * 1允许提现，0禁止
   * @return allowWithdraw
   */
  @javax.annotation.Nullable
  public Integer getAllowWithdraw() {
    return allowWithdraw;
  }

  public void setAllowWithdraw(@javax.annotation.Nullable Integer allowWithdraw) {
    this.allowWithdraw = allowWithdraw;
  }


  public Token depositMinQuantity(@javax.annotation.Nullable String depositMinQuantity) {
    this.depositMinQuantity = depositMinQuantity;
    return this;
  }

  /**
   * 充币最小额度。小于这个额度，不入账
   * @return depositMinQuantity
   */
  @javax.annotation.Nullable
  public String getDepositMinQuantity() {
    return depositMinQuantity;
  }

  public void setDepositMinQuantity(@javax.annotation.Nullable String depositMinQuantity) {
    this.depositMinQuantity = depositMinQuantity;
  }


  public Token withdrawMinQuantity(@javax.annotation.Nullable String withdrawMinQuantity) {
    this.withdrawMinQuantity = withdrawMinQuantity;
    return this;
  }

  /**
   * 提币的最小额度
   * @return withdrawMinQuantity
   */
  @javax.annotation.Nullable
  public String getWithdrawMinQuantity() {
    return withdrawMinQuantity;
  }

  public void setWithdrawMinQuantity(@javax.annotation.Nullable String withdrawMinQuantity) {
    this.withdrawMinQuantity = withdrawMinQuantity;
  }


  public Token withdrawMaxDayQuantity(@javax.annotation.Nullable String withdrawMaxDayQuantity) {
    this.withdrawMaxDayQuantity = withdrawMaxDayQuantity;
    return this;
  }

  /**
   * 该币种提币的最大额度
   * @return withdrawMaxDayQuantity
   */
  @javax.annotation.Nullable
  public String getWithdrawMaxDayQuantity() {
    return withdrawMaxDayQuantity;
  }

  public void setWithdrawMaxDayQuantity(@javax.annotation.Nullable String withdrawMaxDayQuantity) {
    this.withdrawMaxDayQuantity = withdrawMaxDayQuantity;
  }


  public Token depositCharges(@javax.annotation.Nullable String depositCharges) {
    this.depositCharges = depositCharges;
    return this;
  }

  /**
   * 充币手续费百分比---broker 新配置
   * @return depositCharges
   */
  @javax.annotation.Nullable
  public String getDepositCharges() {
    return depositCharges;
  }

  public void setDepositCharges(@javax.annotation.Nullable String depositCharges) {
    this.depositCharges = depositCharges;
  }


  public Token depositChargesMinAmount(@javax.annotation.Nullable String depositChargesMinAmount) {
    this.depositChargesMinAmount = depositChargesMinAmount;
    return this;
  }

  /**
   * 充币的最小手续费---broker 新配置
   * @return depositChargesMinAmount
   */
  @javax.annotation.Nullable
  public String getDepositChargesMinAmount() {
    return depositChargesMinAmount;
  }

  public void setDepositChargesMinAmount(@javax.annotation.Nullable String depositChargesMinAmount) {
    this.depositChargesMinAmount = depositChargesMinAmount;
  }


  public Token withdrawalChargesMinAmount(@javax.annotation.Nullable String withdrawalChargesMinAmount) {
    this.withdrawalChargesMinAmount = withdrawalChargesMinAmount;
    return this;
  }

  /**
   * 提币的最小手续费---broker 新配置
   * @return withdrawalChargesMinAmount
   */
  @javax.annotation.Nullable
  public String getWithdrawalChargesMinAmount() {
    return withdrawalChargesMinAmount;
  }

  public void setWithdrawalChargesMinAmount(@javax.annotation.Nullable String withdrawalChargesMinAmount) {
    this.withdrawalChargesMinAmount = withdrawalChargesMinAmount;
  }


  public Token withdrawChargeValue(@javax.annotation.Nullable String withdrawChargeValue) {
    this.withdrawChargeValue = withdrawChargeValue;
    return this;
  }

  /**
   * 提币百分比手续费
   * @return withdrawChargeValue
   */
  @javax.annotation.Nullable
  public String getWithdrawChargeValue() {
    return withdrawChargeValue;
  }

  public void setWithdrawChargeValue(@javax.annotation.Nullable String withdrawChargeValue) {
    this.withdrawChargeValue = withdrawChargeValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Token token = (Token) o;
    return Objects.equals(this.id, token.id) &&
        Objects.equals(this.tokenId, token.tokenId) &&
        Objects.equals(this.tokenName, token.tokenName) &&
        Objects.equals(this.tokenFullName, token.tokenFullName) &&
        Objects.equals(this.chainId, token.chainId) &&
        Objects.equals(this.createdAt, token.createdAt) &&
        Objects.equals(this.updatedAt, token.updatedAt) &&
        Objects.equals(this.icon, token.icon) &&
        Objects.equals(this.protocolName, token.protocolName) &&
        Objects.equals(this.chainName, token.chainName) &&
        Objects.equals(this.chainIcon, token.chainIcon) &&
        Objects.equals(this.status, token.status) &&
        Objects.equals(this.allowDeposit, token.allowDeposit) &&
        Objects.equals(this.allowWithdraw, token.allowWithdraw) &&
        Objects.equals(this.depositMinQuantity, token.depositMinQuantity) &&
        Objects.equals(this.withdrawMinQuantity, token.withdrawMinQuantity) &&
        Objects.equals(this.withdrawMaxDayQuantity, token.withdrawMaxDayQuantity) &&
        Objects.equals(this.depositCharges, token.depositCharges) &&
        Objects.equals(this.depositChargesMinAmount, token.depositChargesMinAmount) &&
        Objects.equals(this.withdrawalChargesMinAmount, token.withdrawalChargesMinAmount) &&
        Objects.equals(this.withdrawChargeValue, token.withdrawChargeValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tokenId, tokenName, tokenFullName, chainId, createdAt, updatedAt, icon, protocolName, chainName, chainIcon, status, allowDeposit, allowWithdraw, depositMinQuantity, withdrawMinQuantity, withdrawMaxDayQuantity, depositCharges, depositChargesMinAmount, withdrawalChargesMinAmount, withdrawChargeValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Token {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    tokenFullName: ").append(toIndentedString(tokenFullName)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    protocolName: ").append(toIndentedString(protocolName)).append("\n");
    sb.append("    chainName: ").append(toIndentedString(chainName)).append("\n");
    sb.append("    chainIcon: ").append(toIndentedString(chainIcon)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    allowDeposit: ").append(toIndentedString(allowDeposit)).append("\n");
    sb.append("    allowWithdraw: ").append(toIndentedString(allowWithdraw)).append("\n");
    sb.append("    depositMinQuantity: ").append(toIndentedString(depositMinQuantity)).append("\n");
    sb.append("    withdrawMinQuantity: ").append(toIndentedString(withdrawMinQuantity)).append("\n");
    sb.append("    withdrawMaxDayQuantity: ").append(toIndentedString(withdrawMaxDayQuantity)).append("\n");
    sb.append("    depositCharges: ").append(toIndentedString(depositCharges)).append("\n");
    sb.append("    depositChargesMinAmount: ").append(toIndentedString(depositChargesMinAmount)).append("\n");
    sb.append("    withdrawalChargesMinAmount: ").append(toIndentedString(withdrawalChargesMinAmount)).append("\n");
    sb.append("    withdrawChargeValue: ").append(toIndentedString(withdrawChargeValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("tokenId");
    openapiFields.add("tokenName");
    openapiFields.add("tokenFullName");
    openapiFields.add("chainId");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("icon");
    openapiFields.add("protocolName");
    openapiFields.add("chainName");
    openapiFields.add("chainIcon");
    openapiFields.add("status");
    openapiFields.add("allowDeposit");
    openapiFields.add("allowWithdraw");
    openapiFields.add("depositMinQuantity");
    openapiFields.add("withdrawMinQuantity");
    openapiFields.add("withdrawMaxDayQuantity");
    openapiFields.add("depositCharges");
    openapiFields.add("depositChargesMinAmount");
    openapiFields.add("withdrawalChargesMinAmount");
    openapiFields.add("withdrawChargeValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Token
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Token.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Token is not found in the empty JSON string", Token.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Token.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Token` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("tokenId") != null && !jsonObj.get("tokenId").isJsonNull()) && !jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if ((jsonObj.get("tokenName") != null && !jsonObj.get("tokenName").isJsonNull()) && !jsonObj.get("tokenName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenName").toString()));
      }
      if ((jsonObj.get("tokenFullName") != null && !jsonObj.get("tokenFullName").isJsonNull()) && !jsonObj.get("tokenFullName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenFullName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenFullName").toString()));
      }
      if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull()) && !jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("icon") != null && !jsonObj.get("icon").isJsonNull()) && !jsonObj.get("icon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `icon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("icon").toString()));
      }
      if ((jsonObj.get("protocolName") != null && !jsonObj.get("protocolName").isJsonNull()) && !jsonObj.get("protocolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `protocolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("protocolName").toString()));
      }
      if ((jsonObj.get("chainName") != null && !jsonObj.get("chainName").isJsonNull()) && !jsonObj.get("chainName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainName").toString()));
      }
      if ((jsonObj.get("chainIcon") != null && !jsonObj.get("chainIcon").isJsonNull()) && !jsonObj.get("chainIcon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainIcon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainIcon").toString()));
      }
      if ((jsonObj.get("depositMinQuantity") != null && !jsonObj.get("depositMinQuantity").isJsonNull()) && !jsonObj.get("depositMinQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `depositMinQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("depositMinQuantity").toString()));
      }
      if ((jsonObj.get("withdrawMinQuantity") != null && !jsonObj.get("withdrawMinQuantity").isJsonNull()) && !jsonObj.get("withdrawMinQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `withdrawMinQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("withdrawMinQuantity").toString()));
      }
      if ((jsonObj.get("withdrawMaxDayQuantity") != null && !jsonObj.get("withdrawMaxDayQuantity").isJsonNull()) && !jsonObj.get("withdrawMaxDayQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `withdrawMaxDayQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("withdrawMaxDayQuantity").toString()));
      }
      if ((jsonObj.get("depositCharges") != null && !jsonObj.get("depositCharges").isJsonNull()) && !jsonObj.get("depositCharges").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `depositCharges` to be a primitive type in the JSON string but got `%s`", jsonObj.get("depositCharges").toString()));
      }
      if ((jsonObj.get("depositChargesMinAmount") != null && !jsonObj.get("depositChargesMinAmount").isJsonNull()) && !jsonObj.get("depositChargesMinAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `depositChargesMinAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("depositChargesMinAmount").toString()));
      }
      if ((jsonObj.get("withdrawalChargesMinAmount") != null && !jsonObj.get("withdrawalChargesMinAmount").isJsonNull()) && !jsonObj.get("withdrawalChargesMinAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `withdrawalChargesMinAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("withdrawalChargesMinAmount").toString()));
      }
      if ((jsonObj.get("withdrawChargeValue") != null && !jsonObj.get("withdrawChargeValue").isJsonNull()) && !jsonObj.get("withdrawChargeValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `withdrawChargeValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("withdrawChargeValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Token.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Token' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Token> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Token.class));

       return (TypeAdapter<T>) new TypeAdapter<Token>() {
           @Override
           public void write(JsonWriter out, Token value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Token read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Token given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Token
   * @throws IOException if the JSON string is invalid with respect to Token
   */
  public static Token fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Token.class);
  }

  /**
   * Convert an instance of Token to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

