/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.paypaz.client.JSON;

/**
 * WithdrawalOrderOpenApiVo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T16:36:57.720967+08:00[Asia/Shanghai]", comments = "Generator version: 7.13.0")
public class WithdrawalOrderOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID = "clientWithdrawalId";
  @SerializedName(SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID)
  @javax.annotation.Nullable
  private String clientWithdrawalId;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nullable
  private String transactionId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @javax.annotation.Nullable
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";
  @SerializedName(SERIALIZED_NAME_CHAIN_ID)
  @javax.annotation.Nullable
  private String chainId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  @javax.annotation.Nullable
  private String subUserId;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_PLATFORM_FEE = "platformFee";
  @SerializedName(SERIALIZED_NAME_PLATFORM_FEE)
  @javax.annotation.Nullable
  private String platformFee;

  public static final String SERIALIZED_NAME_ARRIVE_QUANTITY = "arriveQuantity";
  @SerializedName(SERIALIZED_NAME_ARRIVE_QUANTITY)
  @javax.annotation.Nullable
  private String arriveQuantity;

  public static final String SERIALIZED_NAME_STATUS_INFO = "statusInfo";
  @SerializedName(SERIALIZED_NAME_STATUS_INFO)
  @javax.annotation.Nullable
  private Integer statusInfo;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_ARRIVE_TIME = "arriveTime";
  @SerializedName(SERIALIZED_NAME_ARRIVE_TIME)
  @javax.annotation.Nullable
  private String arriveTime;

  public static final String SERIALIZED_NAME_TOTAL_QUANTITY = "totalQuantity";
  @SerializedName(SERIALIZED_NAME_TOTAL_QUANTITY)
  @javax.annotation.Nullable
  private String totalQuantity;

  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  @javax.annotation.Nullable
  private String txId;

  public WithdrawalOrderOpenApiVo() {
  }

  public WithdrawalOrderOpenApiVo id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * 平台生成
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public WithdrawalOrderOpenApiVo clientWithdrawalId(@javax.annotation.Nullable String clientWithdrawalId) {
    this.clientWithdrawalId = clientWithdrawalId;
    return this;
  }

  /**
   * 客户端订单ID
   * @return clientWithdrawalId
   */
  @javax.annotation.Nullable
  public String getClientWithdrawalId() {
    return clientWithdrawalId;
  }

  public void setClientWithdrawalId(@javax.annotation.Nullable String clientWithdrawalId) {
    this.clientWithdrawalId = clientWithdrawalId;
  }


  public WithdrawalOrderOpenApiVo transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * 订单ID
   * @return transactionId
   */
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public WithdrawalOrderOpenApiVo tokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * tokenId
   * @return tokenId
   */
  @javax.annotation.Nullable
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(@javax.annotation.Nullable String tokenId) {
    this.tokenId = tokenId;
  }


  public WithdrawalOrderOpenApiVo chainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
    return this;
  }

  /**
   * 链tokenId
   * @return chainId
   */
  @javax.annotation.Nullable
  public String getChainId() {
    return chainId;
  }

  public void setChainId(@javax.annotation.Nullable String chainId) {
    this.chainId = chainId;
  }


  public WithdrawalOrderOpenApiVo userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public WithdrawalOrderOpenApiVo subUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
    return this;
  }

  /**
   * 企业-子用户id
   * @return subUserId
   */
  @javax.annotation.Nullable
  public String getSubUserId() {
    return subUserId;
  }

  public void setSubUserId(@javax.annotation.Nullable String subUserId) {
    this.subUserId = subUserId;
  }


  public WithdrawalOrderOpenApiVo address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * 提现地址 用户的
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public WithdrawalOrderOpenApiVo platformFee(@javax.annotation.Nullable String platformFee) {
    this.platformFee = platformFee;
    return this;
  }

  /**
   * 手续费
   * @return platformFee
   */
  @javax.annotation.Nullable
  public String getPlatformFee() {
    return platformFee;
  }

  public void setPlatformFee(@javax.annotation.Nullable String platformFee) {
    this.platformFee = platformFee;
  }


  public WithdrawalOrderOpenApiVo arriveQuantity(@javax.annotation.Nullable String arriveQuantity) {
    this.arriveQuantity = arriveQuantity;
    return this;
  }

  /**
   * 实际提币数量
   * @return arriveQuantity
   */
  @javax.annotation.Nullable
  public String getArriveQuantity() {
    return arriveQuantity;
  }

  public void setArriveQuantity(@javax.annotation.Nullable String arriveQuantity) {
    this.arriveQuantity = arriveQuantity;
  }


  public WithdrawalOrderOpenApiVo statusInfo(@javax.annotation.Nullable Integer statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

  /**
   * 1,提币处理  2，提币成功， 3，提币失败
   * @return statusInfo
   */
  @javax.annotation.Nullable
  public Integer getStatusInfo() {
    return statusInfo;
  }

  public void setStatusInfo(@javax.annotation.Nullable Integer statusInfo) {
    this.statusInfo = statusInfo;
  }


  public WithdrawalOrderOpenApiVo createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * 创建时间
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public WithdrawalOrderOpenApiVo updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * 更新时间
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public WithdrawalOrderOpenApiVo arriveTime(@javax.annotation.Nullable String arriveTime) {
    this.arriveTime = arriveTime;
    return this;
  }

  /**
   * 提现到账时间
   * @return arriveTime
   */
  @javax.annotation.Nullable
  public String getArriveTime() {
    return arriveTime;
  }

  public void setArriveTime(@javax.annotation.Nullable String arriveTime) {
    this.arriveTime = arriveTime;
  }


  public WithdrawalOrderOpenApiVo totalQuantity(@javax.annotation.Nullable String totalQuantity) {
    this.totalQuantity = totalQuantity;
    return this;
  }

  /**
   * 用户输入的提现数量
   * @return totalQuantity
   */
  @javax.annotation.Nullable
  public String getTotalQuantity() {
    return totalQuantity;
  }

  public void setTotalQuantity(@javax.annotation.Nullable String totalQuantity) {
    this.totalQuantity = totalQuantity;
  }


  public WithdrawalOrderOpenApiVo txId(@javax.annotation.Nullable String txId) {
    this.txId = txId;
    return this;
  }

  /**
   * transaction hash
   * @return txId
   */
  @javax.annotation.Nullable
  public String getTxId() {
    return txId;
  }

  public void setTxId(@javax.annotation.Nullable String txId) {
    this.txId = txId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WithdrawalOrderOpenApiVo withdrawalOrderOpenApiVo = (WithdrawalOrderOpenApiVo) o;
    return Objects.equals(this.id, withdrawalOrderOpenApiVo.id) &&
        Objects.equals(this.clientWithdrawalId, withdrawalOrderOpenApiVo.clientWithdrawalId) &&
        Objects.equals(this.transactionId, withdrawalOrderOpenApiVo.transactionId) &&
        Objects.equals(this.tokenId, withdrawalOrderOpenApiVo.tokenId) &&
        Objects.equals(this.chainId, withdrawalOrderOpenApiVo.chainId) &&
        Objects.equals(this.userId, withdrawalOrderOpenApiVo.userId) &&
        Objects.equals(this.subUserId, withdrawalOrderOpenApiVo.subUserId) &&
        Objects.equals(this.address, withdrawalOrderOpenApiVo.address) &&
        Objects.equals(this.platformFee, withdrawalOrderOpenApiVo.platformFee) &&
        Objects.equals(this.arriveQuantity, withdrawalOrderOpenApiVo.arriveQuantity) &&
        Objects.equals(this.statusInfo, withdrawalOrderOpenApiVo.statusInfo) &&
        Objects.equals(this.createdAt, withdrawalOrderOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, withdrawalOrderOpenApiVo.updatedAt) &&
        Objects.equals(this.arriveTime, withdrawalOrderOpenApiVo.arriveTime) &&
        Objects.equals(this.totalQuantity, withdrawalOrderOpenApiVo.totalQuantity) &&
        Objects.equals(this.txId, withdrawalOrderOpenApiVo.txId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientWithdrawalId, transactionId, tokenId, chainId, userId, subUserId, address, platformFee, arriveQuantity, statusInfo, createdAt, updatedAt, arriveTime, totalQuantity, txId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WithdrawalOrderOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientWithdrawalId: ").append(toIndentedString(clientWithdrawalId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    platformFee: ").append(toIndentedString(platformFee)).append("\n");
    sb.append("    arriveQuantity: ").append(toIndentedString(arriveQuantity)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    arriveTime: ").append(toIndentedString(arriveTime)).append("\n");
    sb.append("    totalQuantity: ").append(toIndentedString(totalQuantity)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("clientWithdrawalId");
    openapiFields.add("transactionId");
    openapiFields.add("tokenId");
    openapiFields.add("chainId");
    openapiFields.add("userId");
    openapiFields.add("subUserId");
    openapiFields.add("address");
    openapiFields.add("platformFee");
    openapiFields.add("arriveQuantity");
    openapiFields.add("statusInfo");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("arriveTime");
    openapiFields.add("totalQuantity");
    openapiFields.add("txId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WithdrawalOrderOpenApiVo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WithdrawalOrderOpenApiVo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WithdrawalOrderOpenApiVo is not found in the empty JSON string", WithdrawalOrderOpenApiVo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WithdrawalOrderOpenApiVo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WithdrawalOrderOpenApiVo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("clientWithdrawalId") != null && !jsonObj.get("clientWithdrawalId").isJsonNull()) && !jsonObj.get("clientWithdrawalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientWithdrawalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientWithdrawalId").toString()));
      }
      if ((jsonObj.get("transactionId") != null && !jsonObj.get("transactionId").isJsonNull()) && !jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if ((jsonObj.get("tokenId") != null && !jsonObj.get("tokenId").isJsonNull()) && !jsonObj.get("tokenId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenId").toString()));
      }
      if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull()) && !jsonObj.get("chainId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `chainId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chainId").toString()));
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("subUserId") != null && !jsonObj.get("subUserId").isJsonNull()) && !jsonObj.get("subUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subUserId").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("platformFee") != null && !jsonObj.get("platformFee").isJsonNull()) && !jsonObj.get("platformFee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `platformFee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platformFee").toString()));
      }
      if ((jsonObj.get("arriveQuantity") != null && !jsonObj.get("arriveQuantity").isJsonNull()) && !jsonObj.get("arriveQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `arriveQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("arriveQuantity").toString()));
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
      if ((jsonObj.get("arriveTime") != null && !jsonObj.get("arriveTime").isJsonNull()) && !jsonObj.get("arriveTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `arriveTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("arriveTime").toString()));
      }
      if ((jsonObj.get("totalQuantity") != null && !jsonObj.get("totalQuantity").isJsonNull()) && !jsonObj.get("totalQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `totalQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("totalQuantity").toString()));
      }
      if ((jsonObj.get("txId") != null && !jsonObj.get("txId").isJsonNull()) && !jsonObj.get("txId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `txId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("txId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WithdrawalOrderOpenApiVo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WithdrawalOrderOpenApiVo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WithdrawalOrderOpenApiVo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WithdrawalOrderOpenApiVo.class));

       return (TypeAdapter<T>) new TypeAdapter<WithdrawalOrderOpenApiVo>() {
           @Override
           public void write(JsonWriter out, WithdrawalOrderOpenApiVo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WithdrawalOrderOpenApiVo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WithdrawalOrderOpenApiVo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WithdrawalOrderOpenApiVo
   * @throws IOException if the JSON string is invalid with respect to WithdrawalOrderOpenApiVo
   */
  public static WithdrawalOrderOpenApiVo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WithdrawalOrderOpenApiVo.class);
  }

  /**
   * Convert an instance of WithdrawalOrderOpenApiVo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

