/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * WithdrawalOrderOpenApiVo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-13T11:09:51.307434+08:00[Asia/Shanghai]")
public class WithdrawalOrderOpenApiVo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID = "clientWithdrawalId";
  @SerializedName(SERIALIZED_NAME_CLIENT_WITHDRAWAL_ID)
  private String clientWithdrawalId;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  private String tokenId;

  public static final String SERIALIZED_NAME_CHAIN_TOKEN_ID = "chainTokenId";
  @SerializedName(SERIALIZED_NAME_CHAIN_TOKEN_ID)
  private String chainTokenId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_SUB_USER_ID = "subUserId";
  @SerializedName(SERIALIZED_NAME_SUB_USER_ID)
  private String subUserId;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_PLATFORM_FEE = "platformFee";
  @SerializedName(SERIALIZED_NAME_PLATFORM_FEE)
  private String platformFee;

  public static final String SERIALIZED_NAME_ARRIVE_QUANTITY = "arriveQuantity";
  @SerializedName(SERIALIZED_NAME_ARRIVE_QUANTITY)
  private String arriveQuantity;

  public static final String SERIALIZED_NAME_STATUS_INFO = "statusInfo";
  @SerializedName(SERIALIZED_NAME_STATUS_INFO)
  private Integer statusInfo;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_ARRIVE_TIME = "arriveTime";
  @SerializedName(SERIALIZED_NAME_ARRIVE_TIME)
  private String arriveTime;

  public static final String SERIALIZED_NAME_TOTAL_QUANTITY = "totalQuantity";
  @SerializedName(SERIALIZED_NAME_TOTAL_QUANTITY)
  private String totalQuantity;

  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;


  public WithdrawalOrderOpenApiVo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 平台生成
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "平台生成")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public WithdrawalOrderOpenApiVo clientWithdrawalId(String clientWithdrawalId) {
    
    this.clientWithdrawalId = clientWithdrawalId;
    return this;
  }

   /**
   * 客户端订单ID
   * @return clientWithdrawalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "客户端订单ID")

  public String getClientWithdrawalId() {
    return clientWithdrawalId;
  }


  public void setClientWithdrawalId(String clientWithdrawalId) {
    this.clientWithdrawalId = clientWithdrawalId;
  }


  public WithdrawalOrderOpenApiVo transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * 订单ID
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "订单ID")

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public WithdrawalOrderOpenApiVo tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * tokenId
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "tokenId")

  public String getTokenId() {
    return tokenId;
  }


  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public WithdrawalOrderOpenApiVo chainTokenId(String chainTokenId) {
    
    this.chainTokenId = chainTokenId;
    return this;
  }

   /**
   * 链tokenId
   * @return chainTokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "链tokenId")

  public String getChainTokenId() {
    return chainTokenId;
  }


  public void setChainTokenId(String chainTokenId) {
    this.chainTokenId = chainTokenId;
  }


  public WithdrawalOrderOpenApiVo userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public WithdrawalOrderOpenApiVo subUserId(String subUserId) {
    
    this.subUserId = subUserId;
    return this;
  }

   /**
   * 企业-子用户id
   * @return subUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "企业-子用户id")

  public String getSubUserId() {
    return subUserId;
  }


  public void setSubUserId(String subUserId) {
    this.subUserId = subUserId;
  }


  public WithdrawalOrderOpenApiVo address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * 提现地址 用户的
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "提现地址 用户的")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public WithdrawalOrderOpenApiVo platformFee(String platformFee) {
    
    this.platformFee = platformFee;
    return this;
  }

   /**
   * 手续费
   * @return platformFee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "手续费")

  public String getPlatformFee() {
    return platformFee;
  }


  public void setPlatformFee(String platformFee) {
    this.platformFee = platformFee;
  }


  public WithdrawalOrderOpenApiVo arriveQuantity(String arriveQuantity) {
    
    this.arriveQuantity = arriveQuantity;
    return this;
  }

   /**
   * 实际提币数量
   * @return arriveQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "实际提币数量")

  public String getArriveQuantity() {
    return arriveQuantity;
  }


  public void setArriveQuantity(String arriveQuantity) {
    this.arriveQuantity = arriveQuantity;
  }


  public WithdrawalOrderOpenApiVo statusInfo(Integer statusInfo) {
    
    this.statusInfo = statusInfo;
    return this;
  }

   /**
   * 1,提币处理  2，提币成功， 3，提币失败
   * @return statusInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1,提币处理  2，提币成功， 3，提币失败")

  public Integer getStatusInfo() {
    return statusInfo;
  }


  public void setStatusInfo(Integer statusInfo) {
    this.statusInfo = statusInfo;
  }


  public WithdrawalOrderOpenApiVo createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * 创建时间
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "创建时间")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public WithdrawalOrderOpenApiVo updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 更新时间
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "更新时间")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public WithdrawalOrderOpenApiVo arriveTime(String arriveTime) {
    
    this.arriveTime = arriveTime;
    return this;
  }

   /**
   * 提现到账时间
   * @return arriveTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "提现到账时间")

  public String getArriveTime() {
    return arriveTime;
  }


  public void setArriveTime(String arriveTime) {
    this.arriveTime = arriveTime;
  }


  public WithdrawalOrderOpenApiVo totalQuantity(String totalQuantity) {
    
    this.totalQuantity = totalQuantity;
    return this;
  }

   /**
   * 用户输入的提现数量
   * @return totalQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "用户输入的提现数量")

  public String getTotalQuantity() {
    return totalQuantity;
  }


  public void setTotalQuantity(String totalQuantity) {
    this.totalQuantity = totalQuantity;
  }


  public WithdrawalOrderOpenApiVo txId(String txId) {
    
    this.txId = txId;
    return this;
  }

   /**
   * transaction hash
   * @return txId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "transaction hash")

  public String getTxId() {
    return txId;
  }


  public void setTxId(String txId) {
    this.txId = txId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WithdrawalOrderOpenApiVo withdrawalOrderOpenApiVo = (WithdrawalOrderOpenApiVo) o;
    return Objects.equals(this.id, withdrawalOrderOpenApiVo.id) &&
        Objects.equals(this.clientWithdrawalId, withdrawalOrderOpenApiVo.clientWithdrawalId) &&
        Objects.equals(this.transactionId, withdrawalOrderOpenApiVo.transactionId) &&
        Objects.equals(this.tokenId, withdrawalOrderOpenApiVo.tokenId) &&
        Objects.equals(this.chainTokenId, withdrawalOrderOpenApiVo.chainTokenId) &&
        Objects.equals(this.userId, withdrawalOrderOpenApiVo.userId) &&
        Objects.equals(this.subUserId, withdrawalOrderOpenApiVo.subUserId) &&
        Objects.equals(this.address, withdrawalOrderOpenApiVo.address) &&
        Objects.equals(this.platformFee, withdrawalOrderOpenApiVo.platformFee) &&
        Objects.equals(this.arriveQuantity, withdrawalOrderOpenApiVo.arriveQuantity) &&
        Objects.equals(this.statusInfo, withdrawalOrderOpenApiVo.statusInfo) &&
        Objects.equals(this.createdAt, withdrawalOrderOpenApiVo.createdAt) &&
        Objects.equals(this.updatedAt, withdrawalOrderOpenApiVo.updatedAt) &&
        Objects.equals(this.arriveTime, withdrawalOrderOpenApiVo.arriveTime) &&
        Objects.equals(this.totalQuantity, withdrawalOrderOpenApiVo.totalQuantity) &&
        Objects.equals(this.txId, withdrawalOrderOpenApiVo.txId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientWithdrawalId, transactionId, tokenId, chainTokenId, userId, subUserId, address, platformFee, arriveQuantity, statusInfo, createdAt, updatedAt, arriveTime, totalQuantity, txId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WithdrawalOrderOpenApiVo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientWithdrawalId: ").append(toIndentedString(clientWithdrawalId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    chainTokenId: ").append(toIndentedString(chainTokenId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    subUserId: ").append(toIndentedString(subUserId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    platformFee: ").append(toIndentedString(platformFee)).append("\n");
    sb.append("    arriveQuantity: ").append(toIndentedString(arriveQuantity)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    arriveTime: ").append(toIndentedString(arriveTime)).append("\n");
    sb.append("    totalQuantity: ").append(toIndentedString(totalQuantity)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

