/*
 * paypaz-openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DepositOrderOpenApiVo
 */
public class DepositOrderOpenApiVoTest {
    private final DepositOrderOpenApiVo model = new DepositOrderOpenApiVo();

    /**
     * Model tests for DepositOrderOpenApiVo
     */
    @Test
    public void testDepositOrderOpenApiVo() {
        // TODO: test DepositOrderOpenApiVo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orderNo'
     */
    @Test
    public void orderNoTest() {
        // TODO: test orderNo
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'chainTokenId'
     */
    @Test
    public void chainTokenIdTest() {
        // TODO: test chainTokenId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'netAmount'
     */
    @Test
    public void netAmountTest() {
        // TODO: test netAmount
    }

    /**
     * Test the property 'fromAddress'
     */
    @Test
    public void fromAddressTest() {
        // TODO: test fromAddress
    }

    /**
     * Test the property 'walletAddress'
     */
    @Test
    public void walletAddressTest() {
        // TODO: test walletAddress
    }

    /**
     * Test the property 'txId'
     */
    @Test
    public void txIdTest() {
        // TODO: test txId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'subUserId'
     */
    @Test
    public void subUserIdTest() {
        // TODO: test subUserId
    }

}
