/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Token
 */
public class TokenTest {
    private final Token model = new Token();

    /**
     * Model tests for Token
     */
    @Test
    public void testToken() {
        // TODO: test Token
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'tokenName'
     */
    @Test
    public void tokenNameTest() {
        // TODO: test tokenName
    }

    /**
     * Test the property 'tokenFullName'
     */
    @Test
    public void tokenFullNameTest() {
        // TODO: test tokenFullName
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'protocolName'
     */
    @Test
    public void protocolNameTest() {
        // TODO: test protocolName
    }

    /**
     * Test the property 'chainName'
     */
    @Test
    public void chainNameTest() {
        // TODO: test chainName
    }

    /**
     * Test the property 'chainIcon'
     */
    @Test
    public void chainIconTest() {
        // TODO: test chainIcon
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'allowDeposit'
     */
    @Test
    public void allowDepositTest() {
        // TODO: test allowDeposit
    }

    /**
     * Test the property 'allowWithdraw'
     */
    @Test
    public void allowWithdrawTest() {
        // TODO: test allowWithdraw
    }

    /**
     * Test the property 'depositMinQuantity'
     */
    @Test
    public void depositMinQuantityTest() {
        // TODO: test depositMinQuantity
    }

    /**
     * Test the property 'withdrawMinQuantity'
     */
    @Test
    public void withdrawMinQuantityTest() {
        // TODO: test withdrawMinQuantity
    }

    /**
     * Test the property 'withdrawMaxDayQuantity'
     */
    @Test
    public void withdrawMaxDayQuantityTest() {
        // TODO: test withdrawMaxDayQuantity
    }

    /**
     * Test the property 'depositCharges'
     */
    @Test
    public void depositChargesTest() {
        // TODO: test depositCharges
    }

    /**
     * Test the property 'depositChargesMinAmount'
     */
    @Test
    public void depositChargesMinAmountTest() {
        // TODO: test depositChargesMinAmount
    }

    /**
     * Test the property 'withdrawalChargesMinAmount'
     */
    @Test
    public void withdrawalChargesMinAmountTest() {
        // TODO: test withdrawalChargesMinAmount
    }

    /**
     * Test the property 'withdrawChargeValue'
     */
    @Test
    public void withdrawChargeValueTest() {
        // TODO: test withdrawChargeValue
    }

}
