/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WithdrawalOrderOpenApiVo
 */
public class WithdrawalOrderOpenApiVoTest {
    private final WithdrawalOrderOpenApiVo model = new WithdrawalOrderOpenApiVo();

    /**
     * Model tests for WithdrawalOrderOpenApiVo
     */
    @Test
    public void testWithdrawalOrderOpenApiVo() {
        // TODO: test WithdrawalOrderOpenApiVo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'clientWithdrawalId'
     */
    @Test
    public void clientWithdrawalIdTest() {
        // TODO: test clientWithdrawalId
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'subUserId'
     */
    @Test
    public void subUserIdTest() {
        // TODO: test subUserId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'platformFee'
     */
    @Test
    public void platformFeeTest() {
        // TODO: test platformFee
    }

    /**
     * Test the property 'arriveQuantity'
     */
    @Test
    public void arriveQuantityTest() {
        // TODO: test arriveQuantity
    }

    /**
     * Test the property 'statusInfo'
     */
    @Test
    public void statusInfoTest() {
        // TODO: test statusInfo
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'arriveTime'
     */
    @Test
    public void arriveTimeTest() {
        // TODO: test arriveTime
    }

    /**
     * Test the property 'totalQuantity'
     */
    @Test
    public void totalQuantityTest() {
        // TODO: test totalQuantity
    }

    /**
     * Test the property 'txId'
     */
    @Test
    public void txIdTest() {
        // TODO: test txId
    }

}
