/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.api;

import org.paypaz.client.ApiException;
import org.paypaz.client.model.QueryWithdrawalOrders500Response;
import org.paypaz.client.model.RListChain;
import org.paypaz.client.model.RLong;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final static DefaultApi api;
     static    {
         api  = new DefaultApi();
        api.setCustomBaseUrl("");
     }



    /**
     * 获取所有的netWork
     *
     * 获取所有的netWork
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void allNetWorkTest() throws ApiException {
        RListChain response = api.allNetWork();
        System.out.println("allNetWork response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取所有的netWork
     *
     * 获取所有的netWork
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void allNetWork_0Test() throws ApiException {
        RListChain response = api.allNetWork_0();
        System.out.println("allNetWork_0 response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取服务器时间
     *
     * 获取服务器时间
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serverTimeTest() throws ApiException {
        RLong response = api.serverTime();
        System.out.println("serverTime response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取服务器时间
     *
     * 获取服务器时间
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serverTime_0Test() throws ApiException {
        RLong response = api.serverTime_0();
        System.out.println("serverTime_0 response: " + response);
        assertNotNull(response);
    }

}
