/*
 * paypaz-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.paypaz.client.api;

import org.paypaz.client.ApiClient;
import org.paypaz.client.ApiException;
import org.paypaz.client.model.CreateWithdrawalRequest;
import org.paypaz.client.model.GetDepositAddressRequest;
import org.paypaz.client.model.QueryDepositOrderRequest;
import org.paypaz.client.model.QueryWithdrawalOrderRequest;
import org.paypaz.client.model.QueryWithdrawalOrders500Response;
import org.paypaz.client.model.RListBalanceOpenApiVo;
import org.paypaz.client.model.RListToken;
import org.paypaz.client.model.RPageDepositOrderOpenApiVo;
import org.paypaz.client.model.RPageWithdrawalOrderOpenApiVo;
import org.paypaz.client.model.RSubWalletAddressOpenApiVo;
import org.paypaz.client.model.RWithdrawalOrderOpenApiVo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaypazBrokerOpenApiApi
 */
public class PaypazBrokerOpenApiApiTest {

    private final static  PaypazBrokerOpenApiApi api ;
    static {
        api = new PaypazBrokerOpenApiApi();
        api.setCustomBaseUrl("");
        ApiClient apiClient = api.getApiClient();
        apiClient.setAPI_KEY("");
        apiClient.setAPI_SECRET("");
    }

    /**
     * 获取该币种下所有的token配置
     *
     * 获取该币种下所有的token配置
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void allTokenTest() throws ApiException {
        String tokenId = "USDT";
        String chainId = "TRON";
        RListToken response = api.allToken(tokenId, chainId);
        System.out.println("allToken response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取该币种下所有的token配置
     *
     * 获取该币种下所有的token配置
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void allToken_0Test() throws ApiException {
        String tokenId = "USDT";
        String chainId = "TRON";
        RListToken response = api.allToken_0(tokenId, chainId);
        System.out.println("allToken_0 response: " + response);
        assertNotNull(response);
    }

    /**
     * 根据UID发起提币  为指定子用户创建提币订单
     *
     * 根据UID发起提币  为指定子用户创建提币订单
     *
     * @throws ApiException if the Api call fails
     */
    @Test

    public void createWithdrawalTest() throws ApiException {
        CreateWithdrawalRequest createWithdrawalRequest = new CreateWithdrawalRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .address("TH2DzYticEc5MHrzBFsr1ept1cNW22P84X")
                .amount("0.5")
                .clientWithdrawalId("test-withdrawal-" + System.currentTimeMillis())
                .twoFactorAuthentication(true);
        RWithdrawalOrderOpenApiVo response = api.createWithdrawal(createWithdrawalRequest);
        System.out.println("createWithdrawal response: " + response);
        assertNotNull(response);
    }

    /**
     * 根据UID发起提币  为指定子用户创建提币订单
     *
     * 根据UID发起提币  为指定子用户创建提币订单
     *
     * @throws ApiException if the Api call fails
     */
    @Test

    public void createWithdrawal_0Test() throws ApiException {
        CreateWithdrawalRequest createWithdrawalRequest = new CreateWithdrawalRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .address("TH2DzYticEc5MHrzBFsr1ept1cNW22P84X")
                .amount("5")
                .clientWithdrawalId("test-withdrawal-" + System.currentTimeMillis())
                .twoFactorAuthentication(true);
        RWithdrawalOrderOpenApiVo response = api.createWithdrawal_0(createWithdrawalRequest);
        System.out.println("createWithdrawal_0 response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取或创建充值地址  为指定子用户和币种获取充值地址，如果该币种地址不存在，则创建新地址
     *
     * 获取或创建充值地址  为指定子用户和币种获取充值地址，如果该币种地址不存在，则创建新地址
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositAddressTest() throws ApiException {
        GetDepositAddressRequest getDepositAddressRequest = new GetDepositAddressRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON");
        RSubWalletAddressOpenApiVo response = api.getDepositAddress(getDepositAddressRequest);
        System.out.println("getDepositAddress response: " + response);
        assertNotNull(response);
    }

    /**
     * 获取或创建充值地址  为指定子用户和币种获取充值地址，如果该币种地址不存在，则创建新地址
     *
     * 获取或创建充值地址  为指定子用户和币种获取充值地址，如果该币种地址不存在，则创建新地址
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositAddress_0Test() throws ApiException {
        GetDepositAddressRequest getDepositAddressRequest = new GetDepositAddressRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON");
        RSubWalletAddressOpenApiVo response = api.getDepositAddress_0(getDepositAddressRequest);
        System.out.println("getDepositAddress_0 response: " + response);
        assertNotNull(response);
    }

    /**
     * 查询Broker下所有资产信息  查询当前OpenAPI用户下指定币种或所有币种的资产信息
     *
     * 查询Broker下所有资产信息  查询当前OpenAPI用户下指定币种或所有币种的资产信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryBrokerAssetsTest() throws ApiException {
        String tokenId = "USDT";
        RListBalanceOpenApiVo response = api.queryBrokerAssets(tokenId);
        System.out.println("queryBrokerAssets response: " + response);
        assertNotNull(response);
    }

    /**
     * 查询Broker下所有资产信息  查询当前OpenAPI用户下指定币种或所有币种的资产信息
     *
     * 查询Broker下所有资产信息  查询当前OpenAPI用户下指定币种或所有币种的资产信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryBrokerAssets_0Test() throws ApiException {
        String tokenId = "USDT";
        RListBalanceOpenApiVo response = api.queryBrokerAssets_0(tokenId);
        System.out.println("queryBrokerAssets_0 response: " + response);
        assertNotNull(response);
    }

    /**
     * 分页查询充值订单  根据条件查询充值订单列表，支持分页、时间范围、币种、钱包地址等筛选条件
     *
     * 分页查询充值订单  根据条件查询充值订单列表，支持分页、时间范围、币种、钱包地址等筛选条件
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryDepositOrdersTest() throws ApiException {
        QueryDepositOrderRequest queryDepositOrderRequest = new QueryDepositOrderRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .pageNo(1)
                .pageSize(10);
        RPageDepositOrderOpenApiVo response = api.queryDepositOrders(queryDepositOrderRequest);
        System.out.println("queryDepositOrders response: " + response);
        assertNotNull(response);
        assertEquals(200, response.getCode());
    }

    /**
     * 分页查询充值订单  根据条件查询充值订单列表，支持分页、时间范围、币种、钱包地址等筛选条件
     *
     * 分页查询充值订单  根据条件查询充值订单列表，支持分页、时间范围、币种、钱包地址等筛选条件
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryDepositOrders_0Test() throws ApiException {
        QueryDepositOrderRequest queryDepositOrderRequest = new QueryDepositOrderRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .pageNo(1)
                .pageSize(10);
        RPageDepositOrderOpenApiVo response = api.queryDepositOrders_0(queryDepositOrderRequest);
        System.out.println("queryDepositOrders_0 response: " + response);
        assertNotNull(response);
        assertEquals(200, response.getCode());
    }

    /**
     * 根据subUID、地址、订单号查询提币订单  分页查询指定条件下的提币订单列表
     *
     * 根据subUID、地址、订单号查询提币订单  分页查询指定条件下的提币订单列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryWithdrawalOrdersTest() throws ApiException {
        QueryWithdrawalOrderRequest queryWithdrawalOrderRequest = new QueryWithdrawalOrderRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .pageNo(1)
                .pageSize(10);
        RPageWithdrawalOrderOpenApiVo response = api.queryWithdrawalOrders(queryWithdrawalOrderRequest);
        System.out.println("queryWithdrawalOrders response: " + response);
        assertNotNull(response);
        assertEquals(200, response.getCode());
    }

    /**
     * 根据subUID、地址、订单号查询提币订单  分页查询指定条件下的提币订单列表
     *
     * 根据subUID、地址、订单号查询提币订单  分页查询指定条件下的提币订单列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryWithdrawalOrders_0Test() throws ApiException {
        QueryWithdrawalOrderRequest queryWithdrawalOrderRequest = new QueryWithdrawalOrderRequest()
                .clientSubUserId("test-sub-user-001")
                .tokenId("USDT")
                .chainId("TRON")
                .pageNo(1)
                .pageSize(10);
        RPageWithdrawalOrderOpenApiVo response = api.queryWithdrawalOrders_0(queryWithdrawalOrderRequest);
        System.out.println("queryWithdrawalOrders_0 response: " + response);
        assertNotNull(response);
        assertEquals(200, response.getCode());
    }

    /**
     * 查询提币订单详情  根据客户端提币订单ID查询提币订单详细信息
     *
     * 查询提币订单详情  根据客户端提币订单ID查询提币订单详细信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void withdrawalOrderInfoTest() throws ApiException {
        String clientWithdrawalId = "test-withdrawal-1768295513776";
        RWithdrawalOrderOpenApiVo response = api.withdrawalOrderInfo(clientWithdrawalId);
        System.out.println("withdrawalOrderInfo response: " + response);
        assertNotNull(response);
    }

    /**
     * 查询提币订单详情  根据客户端提币订单ID查询提币订单详细信息
     *
     * 查询提币订单详情  根据客户端提币订单ID查询提币订单详细信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled("需要真实的提币订单ID")
    public void withdrawalOrderInfo_0Test() throws ApiException {
        String clientWithdrawalId = "test-withdrawal-id";
        RWithdrawalOrderOpenApiVo response = api.withdrawalOrderInfo_0(clientWithdrawalId);
        System.out.println("withdrawalOrderInfo_0 response: " + response);
        assertNotNull(response);
    }

}
